# Generated by Django 4.2 on 2023-06-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1992-12-12'),
            preserve_default=False,
        ),
    ]
